[package]
name = "howmanysmall/enumerator"
version = "2.2.0"
author = "howmanysmall"
dependencies_root = "./src/enumerator/"
content_root = "./src/enumerator"
license = "MIT"

# [dependencies]
# t = { git = "https://github.com/osyrisrblx/t/" }